version: "2"
services:
  # datastore:
  #   image: busybox
  #   volumes:
  #     - mysql-data:/var/lib/mysql

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - '3307:3306'
    # volumes_from:
    #   - datastore

  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - '3000:3000'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    depends_on:
      - mysql
    networks:
      - default
    volumes:
      - .:/app:cached
    command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
    # volumes_from:
    #   - datastore

# volumes:
#   mysql-data:
#     driver: local
